name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodu indir
        uses: actions/checkout@v4

      - name: Merhaba de
        run: echo "Merhaba! Ä°lk workflow Ã§alÄ±ÅŸtÄ±! ğŸ‰"

      - name: Tarih yazdÄ±r
        run: date

      - name: KlasÃ¶r iÃ§eriÄŸini gÃ¶ster
        run: ls -la